<?php $block = $this->getBlock() ?>

<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>

<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>
<?php $customerUrl = $objectManager->create('Magento\Customer\Model\Url'); ?>

<?php $topLeftBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_1_top_left_link')->setCanUsePanel($canUsePanel)->toHtml(); ?>

<?php $bottomHeaderBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('bottom_block_header')->setCanUsePanel($canUsePanel)->toHtml(); ?>

<div class="middle-header-content">
	<div class="container">
		<div class="middle-content">
			<?php echo $block->getChildHtml('logo') ?>
			<div class="header-links">
				<div class="login-custom-link">
					<?php if($customerSession->isLoggedIn()): ?>
						<a href="<?php echo $customerUrl->getAccountUrl(); ?>"><span class="fa fa-user" aria-hidden="true"></span><span class="username"><?php echo $customerSession->getCustomer()->getName(); ?></span></a>
						<a href="<?php echo $customerUrl->getLogoutUrl(); ?>"><span class="fa fa-sign-out" aria-hidden="true"></span><span class="text"><?php echo __('Logout'); ?></span></a>
					<?php else: ?>
						<a href="<?php echo $customerUrl->getLoginUrl(); ?>"><span class="fa fa-user" aria-hidden="true"></span>
						<span class="text"><?php echo __('Login'); ?><span class="or"> <?php echo __('or'); ?> </span><?php echo __('Register'); ?></span></a>
					<?php endif ?>
				</div>
				<?php echo $block->getChildHtml('minicart') ?>
			</div>
			<div class="megamenu-content<?php if($block->getChildHtml('megamenu')!=''): ?> mgs-menu<?php else: ?> mgt-menu<?php endif ?>">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#main-Menucontent"><?php echo __('Menu'); ?></a></li>
					<li><a data-toggle="tab" href="#main-Accountcontent"><?php echo __('My Account'); ?></a></li>
				</ul>
				<div class="tab-content">
					<div id="main-Menucontent" class="tab-pane active">
						<?php if($block->getChildHtml('megamenu')!=''): ?>
							<?php echo $block->getChildHtml('megamenu') ?>
						<?php else: ?>
							<?php echo $block->getChildHtml('catalog.topnav') ?>
						<?php endif ?>
					</div>
					<div id="main-Accountcontent" class="tab-pane">
						<?php echo $block->getChildHtml('top.links') ?>
						<?php if($topLeftBlock || $topRightBlock): ?>
							<div class="top-custom-link">
								<?php if($topLeftBlock): ?>
									<?php echo $topLeftBlock; ?>
								<?php endif ?>
							</div>
						<?php endif ?>
					</div>
				</div>
			</div>
			<?php echo $block->getChildHtml('top.search') ?>
			<div class="action-menu-responsive visible-sm visible-xs">
				<button class="action nav-toggle"><span class="fa fa-bars" aria-hidden="true"></span></button>
			</div>
			
			<?php if($bottomHeaderBlock): ?>
				<div class="bottom-header-custom-block">
					<!-- Static block: bottom_block_header -->
					<?php echo $bottomHeaderBlock; ?>
				</div>
			<?php endif ?>
		</div>
	</div>
</div>

<button class="action close-nav-button"><span class="fa fa-times" aria-hidden="true"></span></button>

<script type="text/javascript">
require([
	"jquery"
], function($){
	$(document).ready(function(){
		$('body').addClass('menu_vertical_fixed');
		$(".top-header-content").detach().appendTo('#mini_header');
		
		$(".header.header8 .navigation .nav-main-menu > li.mega-menu-fullwidth").hover(function() {
			if($(window).width() > 1199){
				var widthMenu = $(window).width() - 360;
				$(this).find("> .dropdown-menu").width(widthMenu);
			}
		});
	});
	
    $(window).scroll(function () {
        var headerLeftHeight = $(".header.header8").innerHeight();
        var window_height = $(this).height();

        if (headerLeftHeight - window_height < $(this).scrollTop()) {
            if (!$(".header.header8").hasClass("fixed-bottom")) {
                $(".header.header8").addClass("fixed-bottom");
            }
        }
        if (headerLeftHeight - window_height >= $(this).scrollTop()) {
            if ($(".header.header8").hasClass("fixed-bottom")) {
                $(".header.header8").removeClass("fixed-bottom");
            }
        }
    });
});
</script>
