<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $header = $helper->getStoreConfig('mgstheme/general/header') ?>
<?php if($header!=''): ?>
	<?php echo $this->getLayout()->createBlock('Magento\Theme\Block\Html\Header')->setBlock($block)->setTemplate('Magento_Theme::html/headers/'.$header.'.phtml')->toHtml() ?>
<?php else: ?>
	<?php $canUsePanel = $helper->acceptToUsePanel() ?>

	<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
	<?php $customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>
	<?php $customerUrl = $objectManager->create('Magento\Customer\Model\Url'); ?>

	<?php $topLeftBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_1_top_left_link')->setCanUsePanel($canUsePanel)->toHtml(); ?>
	<div class="top-header-content">
		<div class="container">
			<?php echo $block->getChildHtml('store_language') ?>
			
			<?php echo $block->getChildHtml('currency') ?>
			
			<?php if($topLeftBlock): ?>
				<div class="top-custom-link">
					<?php echo $topLeftBlock; ?>
				</div>
			<?php endif ?>
			<?php echo $block->getChildHtml('minicart') ?>
			<div class="login-custom-link">
				<?php if($customerSession->isLoggedIn()): ?>
					<a href="<?php echo $customerUrl->getAccountUrl(); ?>"><span class="fa fa-user" aria-hidden="true"></span><?php echo $customerSession->getCustomer()->getName(); ?></a>
					<a href="<?php echo $customerUrl->getLogoutUrl(); ?>"><span class="fa fa-sign-out" aria-hidden="true"></span><?php echo __('Logout'); ?></a>
				<?php else: ?>
					<a href="<?php echo $customerUrl->getLoginUrl(); ?>"><span class="fa fa-user" aria-hidden="true"></span><?php echo __('Login'); ?><span> <?php echo __('or'); ?> </span><?php echo __('Register'); ?></a>
				<?php endif ?>
			</div>
		</div>
	</div>
	<div class="middle-header-content">
		<?php echo $block->getChildHtml('logo') ?>
	</div>
	<div class="bottom-header-content">
		<div class="container">
			<div class="menu-content">
				<button class="action nav-toggle hidden-lg"><span class="fa fa-bars" aria-hidden="true"></span></button>
				<?php echo $block->getChildHtml('logo') ?>
				<div class="megamenu-content<?php if($block->getChildHtml('megamenu')!=''): ?> mgs-menu<?php else: ?> mgt-menu<?php endif ?>">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#main-Menucontent"><?php echo __('Menu'); ?></a></li>
						<li><a data-toggle="tab" href="#main-Accountcontent"><?php echo __('My Account'); ?></a></li>
					</ul>
					<div class="tab-content">
						<div id="main-Menucontent" class="tab-pane active">
							<?php if($block->getChildHtml('megamenu')!=''): ?>
								<?php echo $block->getChildHtml('megamenu') ?>
							<?php else: ?>
								<?php echo $block->getChildHtml('catalog.topnav') ?>
							<?php endif ?>
						</div>
						<div id="main-Accountcontent" class="tab-pane">
							<?php echo $block->getChildHtml('top.links') ?>
							<?php if($topLeftBlock): ?>
								<div class="top-custom-link">
									<?php echo $topLeftBlock; ?>
								</div>
							<?php endif ?>
						</div>
					</div>
				</div>
				<?php echo $block->getChildHtml('top.search') ?>
			</div>
		</div>
	</div>
	<button class="action close-nav-button"><span class="fa fa-times" aria-hidden="true"></span></button>
<?php endif ?>