<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
?>


<?php $helper = $this->helper('Magento\Search\Helper\Data'); ?>

<?php $mpanelHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>

<?php $enableCategories = $mpanelHelper->getStoreConfig('mpanel/catalogsearch/show_categories'); ?>

<?php if($enableCategories){ $categories = $mpanelHelper->getCategories(); } ?>

<div class="search-form <?php if($enableCategories): ?>select-search<?php endif;?>">
	<div class="form-search">
		<form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
			<?php if($enableCategories): ?>
				<?php $currentCategory = ""; ?>
				<?php $currentCategoryId = ""; ?>
				<?php foreach ($categories as $category) {
						foreach ($category as $key => $value) {
							if ($key == 'label') { $categoryName = $value; }
							if ($key == 'value') { $categoryId = $value; }
						}
						if ($mpanelHelper->getCurrentlySelectedCategoryId() == $categoryId){
							$currentCategory = $categoryName;
							$currentCategoryId = $categoryId;
							break;
						}
					} ?>
				<input type="hidden" name="cat" id="cat" value="<?php echo $currentCategoryId; ?>"/>
				<div class="search-select">
					<div class="dropdown">
						<button id="toggleCatSearch" class="search-toggle dropdown-toggle" type="button" data-toggle="dropdown">
							<span id="cat-active-name" class="search-cat-active">
								<?php if($currentCategory != ""): ?>
									<?php echo $currentCategory ?>
								<?php else: ?>
									<?php echo __('All Categories'); ?>
								<?php endif ?>
							</span>
							<i class="fa fa-angle-down" aria-hidden="true"></i>
						</button>
						<ul id="select-cat-dropdown" class="dropdown-menu">
							<li class="parent">
								<a href="javascript:void(0);" onclick="setSearchCatValue('', '<?php echo __('All Categories') ?>');"><?php echo __('All Categories') ?></a>
							</li>
							<?php
								foreach ($categories as $category) {
									foreach ($category as $key => $value) {
										if ($key == 'label') {
											$categoryName = $value;
										}
										if ($key == 'value') {
											$categoryId = $value;
										}
										if ($key == 'level') {
											$categoryLevel = $value;
										}
									}
									?>
									<li class="<?php if($categoryLevel < 3): ?>parent<?php endif ?> level<?php echo $categoryLevel ?> <?php if ($mpanelHelper->getCurrentlySelectedCategoryId() == $categoryId): ?>active<?php endif; ?>">
										<a href="javascript:void(0);" onclick="setSearchCatValue('<?php echo $categoryId; ?>', '<?php echo $categoryName; ?>');"><?php echo $categoryName; ?></a>
									</li>
									<?php
								}
							?>
						</ul>
					</div>
				</div>
			<?php endif; ?>
			<input id="search"
			   data-mage-init='{"quickSearch":{
					"formSelector":"#search_mini_form",
					"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
					"destinationSelector":"#search_autocomplete"}
			   }'
			   type="text"
			   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
			   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
			   class="input-text form-control"
			   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
			   placeholder="<?php echo __('Type your search here...') ?>"
			   role="combobox"
			   aria-expanded="true"
			   aria-haspopup="false"
			   aria-autocomplete="both"
			   autocomplete="off"/>
				
			<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="button">
				<i class="fa fa-search"></i>
			</button>	   
			<div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
			<?php echo $block->getChildHtml() ?>
		</form>
	</div>
	<div class="actions-search">
		<button class="action-search" onclick="showHideFormSearch()">
			<span class="show-search"><span><?php echo __('Search') ?></span><i class="fa fa-search"></i></span>
			<span class="hide-search"><?php echo __('x') ?></span>
		</button>
	</div>
</div>

<script type="text/javascript">
	<?php if($enableCategories): ?>
		function setSearchCatValue(id,name){
			require([
			'jquery'
			], function(jQuery){
				(function($) {
					$('#cat').val(id);
					$('#cat-active-name').html(name);
				})(jQuery);
			});
		}
	<?php endif ?>
	function showHideFormSearch(){
		require([
		'jquery'
		], function(jQuery){
			(function($) {
				$('.actions-search .action-search').toggleClass('on-show');
				$('.search-form .form-search').toggleClass('on-show');
				$('.search-form').toggleClass('active');
				if($('.header').hasClass('header3')){
					var $widthContent = $('.header.header3 .middle-content').width() - $('.header.header3 .middle-content .logo').width() - $('.header.header3 .middle-content .middle-header-right-content').width();
					$('.header.header3 .search-form .form-search').width($widthContent);
				}
				if($('.header').hasClass('header9')){
					var $widthContent = $('.header.header9 .middle-content').width() - $('.header.header9 .middle-content .logo').width() - $('.header.header9 .middle-content .middle-header-right-content').width();
					$('.header.header9 .search-form .form-search').width($widthContent);
				}
				setTimeout(focusSearchField, 500);
			})(jQuery);
		});
	}
	function focusSearchField(){
		require([
		'jquery'
		], function(jQuery){
			(function($) {
				$('#search_mini_form input#search').focus();
			})(jQuery);
		});
	}
	require([
		'jquery'
	], function(jQuery){
		(function($) {
			$(window).resize(function(){
				if($('.header').hasClass('header3')){
					var $widthContent = $('.header.header3 .middle-content').width() - $('.header.header3 .middle-content .logo').width() - $('.header.header3 .middle-content .middle-header-right-content').width();
					$('.header.header3 .search-form .form-search').width($widthContent);
				}
				if($('.header').hasClass('header9')){
					var $widthContent = $('.header.header9 .middle-content').width() - $('.header.header9 .middle-content .logo').width() - $('.header.header9 .middle-content .middle-header-right-content').width();
					$('.header.header9 .search-form .form-search').width($widthContent);
				}
			});
		})(jQuery);
	});
</script>
