<?php $_productCollection = $this->getDealsByCategories($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<?php $baseImage = $this->getViewFileUrl('MGS_Mpanel::images/blank.png'); ?>
<div class="content-block deal-product-cat-block">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_title')): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if (count($_productCollection)>0): ?>
		
		<?php 
			$blockId = rand() . time();
			$_helper = $this->helper('Magento\Catalog\Helper\Output');
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow();
			if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
				$columnCount = $perRow * $this->getNumberRow();
			}
			$image = 'category_page_grid';
			$image_hover = 'product_base_image';
			$themeSettings = $themeHelper->getThemeSettings();
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		
		<div class="block widget mgs-products deal-products-grid products-grid<?php if($useSlider): ?> row<?php if($this->getNumberRow() == 1): ?> slider-1-row<?php endif ?><?php endif ?>">
			<div class="items<?php if($useSlider): ?> owl-carousel<?php else: ?> row <?php echo $themeHelper->convertColClass($col, 'row') ?><?php endif ?>" id="deal-products<?php echo $blockId; ?>">
				<?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
					<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
						<?php if ($j++ % $columnCount == 0): ?>
							<div class="item">
						<?php endif ?>
					<?php endif ?>
					<div class="<?php if(!$useSlider || $this->getNumberRow()==1): ?>item <?php else: ?><?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?> <?php endif ?>product product-item<?php if(!$useSlider): ?> <?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?><?php endif ?>">
						<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
						<div class="product-item-info" data-container="product-grid">
							<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$size = $themeHelper->getImageSize($this->getRatio());
								$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
								if(!$lazyLoad){
									$baseImage = $productImage;
								}
							?>
							<div class="product-top">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>" data-<?php if($useSlider): ?>src<?php else: ?>original<?php endif ?>="<?php echo $productImage ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> <?php if($useSlider): ?>owl-<?php endif ?>lazy<?php endif ?>" />
								</a>
								<?php echo $themeHelper->getProductLabel($_product) ?>
								<ul class="actions-link">
									<li class="hidden-sm hidden-xs">
										<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
										<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
									</li>
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
										<li>
											<button class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-title="<?php echo __('Add to Wish List') ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<i class="fa fa-heart"></i>
											</button>
										</li>
									<?php endif; ?>
									<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
									<?php if(!$themeSettings['catalog']['compare_button']): ?>
										<li>
											<button class="action tocompare"
											   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-title="<?php echo __('Add to Compare') ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
											   role="button">
												<i class="fa fa-random"></i>
											</button>
										</li>
									<?php endif ?>
									<?php if ($_product->isSaleable()): ?>
										<li>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
												<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
												<button class="action tocart" type="submit" data-title="<?php echo __('Add to Cart') ?>" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
													<i class="fa fa-shopping-cart"></i>
												</button>
											</form>
										</li>
									<?php endif; ?>
								</ul>
							</div>
							<div class="product details product-item-details">
								<h5 class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h5>
								<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
								
								<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
								
								<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
							</div>
						</div>
					</div>
					<?php if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1): ?>
						<?php if ($j % $columnCount == 0 || $j == count($_productCollection)): ?>
							</div>
						<?php endif ?>
					<?php endif ?>
				<?php endforeach; ?>
			</div>
			
			<?php if($useSlider): ?>
				<?php if($this->hasData('number_row') && $this->getNumberRow()>1):?>
					<?php $perRow = 1; ?>
				<?php endif ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						$('#deal-products<?php echo $blockId ?>').owlCarousel({
							items: <?php echo $perRow; ?>,
							autoplay: <?php echo $autoPlay ?>,
							loop: false,
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							dots: <?php echo $dot ?>,
							lazyLoad: true,
							navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
							<?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
								responsive:{
									0:{
										items:1
									},
									768:{
										items:2
									},
									992:{
										items:<?php echo $perRow; ?>
									}
								}
							<?php endif ?>
						});
					});
				</script>
			
			<?php endif ?>
		</div>	
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no deals matching the selection.') ?></div>
	<?php endif ?>
</div>