<?php $portfolios = $this->getPortfolios() ?>
<?php $helper = $this->helper('MGS\Portfolio\Helper\Data'); ?>
<div class="content-block portfolio-block portfolio-list-block">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_title')): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>

	<?php if(count($portfolios)>0): ?>
		<?php
			$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
			$blockId = rand() . time();
			$useSlider = $this->getUseSlider();
			$showThumbnail = $this->getShowThumbnail();
			$showCategories = $this->getShowCategories();
			$showShowContent = $this->getShowContent();
			$perRow = $this->getPerrow();
			$col = $themeHelper->convertPerRowtoCol($perRow);
		?>
		<?php $bootstrapItem = true; ?>
		<?php if($useSlider): ?>
			<?php 
				if($this->hasData('number_row') && $this->getNumberRow()>1){
					$columnCount = $perRow * $this->getNumberRow();
				}else {
					$bootstrapItem = false;
				}
			?>
		<?php endif ?>
		
		<div class="block widget <?php if($useSlider): ?> row<?php endif ?>">
			<div class="mgs-portfolio-carousel-<?php echo $blockId; ?> portfolio-grid <?php if($useSlider): ?>owl-carousel portfolio-carousel<?php else: ?>row<?php endif ?>">
				<?php $i=0; $j=0; foreach ($portfolios as $portfolio): $i++; ?>
					
					<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
						<?php if ($j++ % $columnCount == 0): ?>
							<div class="items row">
						<?php endif ?>
					<?php endif ?>
						<div class="item <?php if($bootstrapItem): ?> col-md-<?php echo $col ?> <?php if($i % $perRow == 1): ?>first-row-item<?php endif ?> <?php if($i % 2 == 1): ?>first-sm-item<?php endif ?> col-sm-6 col-xs-12<?php endif ?>">
							<div class="item_inner">
								<div class="portfolio-top-content">
										<div class="image">
											<a href="<?php echo $portfolio->getAddress(); ?>"><img src="<?php echo $this->getThumbnailSrc($portfolio)?>" alt="<?php echo $portfolio->getName() ?>" class="img-responsive"/></a>
										</div>
										<div class="actions text-center">
											<a href="<?php echo $portfolio->getAddress(); ?>"><i class="fa fa-search"></i></a>
											<?php if($portfolio->getProjectUrl()): ?>
												<a href="<?php echo $portfolio->getProjectUrl() ?>" target="_blank"><i class="fa fa-link"></i></a>
											<?php endif ?>
										</div>
									</div>
									<div class="portfolio-bottom-content text-center">
										<?php if($showCategories): ?>
											<div class="category-link"><?php echo $this->getCategoriesLink($portfolio)?></div>
										<?php endif ?>
										<a class="title" href="<?php echo $portfolio->getAddress(); ?>"><?php echo $portfolio->getName() ?></a>
									</div>
								</div>
						</div>
					<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
						<?php if ($j % $columnCount == 0 || $j == count($portfolios)): ?>
							</div>
						<?php endif ?>
					<?php endif ?>
					
				<?php endforeach ?>
			</div>
		</div>
		<?php if($useSlider): ?>
			<script type="text/javascript">
				require([
					'jquery',
					'mgs/owlcarousel'
				], function ($) {
					var owl<?php echo $blockId ?> = $('.mgs-portfolio-carousel-<?php echo $blockId ?>').owlCarousel({
						<?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
						items: <?php echo $perRow; ?>,
						<?php else: ?>
						items: 1,
						<?php endif ?>
						autoplay: <?php echo $this->getAutoplay() ? 'true' : 'false' ?>,
						autoplayHoverPause: <?php echo $this->getStopAuto() ? 'true' : 'false' ?>,
						nav: <?php echo $this->getNavigation() ? 'true' : 'false' ?>,
						dots: <?php echo $this->getPagination() ? 'true' : 'false' ?>,
						navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
						<?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
							responsive:{
								0:{
									items:1
								},
								480:{
									items:2
								},
								768:{
									items:<?php echo $perRow; ?>
								}
							}
						<?php endif ?>
					});
					<?php if($this->getPagination()): ?>
						owl<?php echo $blockId ?>.on('changed.owl.carousel', function (event) {
							if (event.item.count - event.page.size == event.item.index)
								$(event.target).find('.owl-dots div:last')
								  .addClass('active').siblings().removeClass('active');
						});
					<?php endif ?>
				});
			</script>
		<?php endif ?>
	<?php else: ?>
		<p class="note-msg"><?php echo $this->__('There are no portfolios matching the selection.') ?></p>
	<?php endif ?>
</div>