<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php $block = $this->getBlock() ?>
<div class="footer-container">
	<div class="middle-footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<!-- Static block: footer_contact_us -->
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_contact_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
					<!-- Static block: footer_block_quick_link -->
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_quick_link')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
					<!-- Static block: footer_block_our_policy -->
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_our_policy')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<!-- Static block: footer_block_product_tag -->
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_product_tag')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
			</div>
		</div>
	</div>
	<div class="bottom-footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 pull-right">
					<!-- Static block: footer_block_social -->
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_social')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
					<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
				</div>
			</div>
		</div>
	</div>
</div>