<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php $block = $this->getBlock() ?>
<div class="footer-container">
	<div class="middle-footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 first">
					<!-- Static block: footer_about_us -->
					<div class="block-middle-item">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_about_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<!-- Static block: footer_block_latest_new -->
					<div class="block-middle-item">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_latest_new')->setCanUsePanel($canUsePanel)->toHtml() ?>
					</div>
				</div>
				<div class="clearfix visible-sm"></div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<!-- Static block: footer_block_product_tag -->
					<div class="block-middle-item">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_product_tag')->setCanUsePanel($canUsePanel)->toHtml() ?>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 last">
					<!-- Static block: footer_block_newsletter -->
					<div class="block-middle-item">
						<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_newsletter')->setCanUsePanel($canUsePanel)->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="bottom-footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pull-right">
					<!-- Static block: footer_block_bottom_link -->
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_block_bottom_link')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
				</div>
			</div>
		</div>
	</div>
</div>