<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$collection = $block->getCollection();
$showThumbnail = $this->getConfig('general_settings/show_thumbnail');
?>
<?php if (!count($collection)): ?>
    <div class="message empty">
        <div><?php echo __('Have no posts.') ?></div>
    </div>
<?php else: ?>
    <div class="blog-list">
        <?php foreach ($collection as $post): ?>
            <div class="blog-post post-item-info">
                <?php if ($showThumbnail): ?>
                    <div class="post-image">
                        <?php echo $helper->getImagePost($post); ?>
						<div class="date-desc">
						    <span class="date">
								<?php echo date('d', strtotime($block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false))) ?>
							</span>
						    <span class="mount">
								<?php echo date('M', strtotime($block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false))) ?>
							</span>
						</div>
                    </div>
                <?php endif; ?>
                <div class="post-info">
				
					<div class="published-by">
						<i class="fa fa-user"></i>
						<?php echo __('By ')?>
						<span class="text-capitalize">
							<?php if ($post->getUpdatedByUser()): ?>
								<?php echo __('%1', $post->getUpdatedByUser()); ?>
							<?php else: ?>
								<?php echo __('%1', $post->getUser()); ?>
							<?php endif; ?>
						</span>
					</div>
					
					<?php if ($post->getTags()): ?>
                    <?php $tags = explode(',', $post->getTags()); ?>
                        <div class="post-tags">
                           <i class="fa fa-tags"></i>
                           <?php foreach ($tags as $tag): ?>
                              <a class="text-capitalize" title="<?php echo trim($tag); ?>" href="<?php echo $helper->getTagUrl(trim($tag)); ?>"><?php echo trim($tag); ?></a>
                           <?php endforeach; ?>
                       </div>
                   <?php endif; ?>
				    
					<?php if ($this->getConfig('comment_settings/enabled')): ?>
						<div class="comment-link">	
						    <i class="fa fa-comment"></i>
							<a href="<?php echo $post->getPostUrlWithNoCategory(); ?>#comment-box">
							<?php echo __('%1 comment(s)', $post->getCommentCount()) ?>
							</a>
						</div>
					<?php endif; ?>
                </div>
                
				<div class="post-content">
					<h2 class="post-title">
						 <a class="post-title-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getPostUrlWithNoCategory(); ?>"><?php echo $post->getTitle(); ?></a>
					</h2>
					<?php if ($post->getShortContent()): ?>
						<div class="post-short-description">
							<?php echo $post->getShortContent(); ?>
						</div>
						<div class="post-link">
							<a class="btn btn-default" title="<?php echo __('Read More'); ?>" href="<?php echo $post->getPostUrlWithNoCategory(); ?>"><?php echo __('Read More'); ?></a>
						</div>
					<?php endif; ?>
				</div>
				
            </div>
        <?php endforeach; ?>
    </div>
    <div class="blog-post-list-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif; ?>
